apitest.base-url=
apitest.connect-timeout-ms=10000
apitest.read-timeout-ms=30000
apitest.write-timeout-ms=30000
apitest.default-content-type=application/json;charset=UTF-8
apitest.default-accept=application/json
apitest.report.enabled=true
apitest.report.dir=target/test-reports
apitest.log.request=true
apitest.log.response=true
